# Generated by Django 4.2 on 2023-05-23 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buzzlab_app', '0002_rename_is_trusty_userprofile_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghours',
            name='is_closed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='additional',
            field=models.CharField(blank=True, max_length=63),
        ),
        migrations.RemoveField(
            model_name='lab',
            name='opening_hours',
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lab',
            name='opening_hours',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buzzlab_app.openinghours'),
            preserve_default=False,
        ),
    ]
