# Generated by Django 4.2 on 2023-05-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzlab_app', '0004_remove_lab_opening_hours_lab_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openinghours',
            name='weekday',
            field=models.CharField(max_length=16),
        ),
    ]
