# Generated by Django 4.2 on 2023-06-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzlab_app', '0005_alter_openinghours_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='description',
            field=models.TextField(blank=True, max_length=1023),
        ),
    ]
