# Generated by Django 4.2 on 2023-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buzzlab_app', '0006_alter_component_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='name',
            field=models.CharField(max_length=127),
        ),
    ]
